const scancodes = [
    { "code": 0, "type": "reserved", "normal": "🔒" },
    { "code": 1, "type": "keyboard", "normal": "FN" },
    { "code": 2, "type": "unknow", "normal": "2" },
    { "code": 3, "type": "unknow", "normal": "3" },
    { "code": 4, "type": "keyboard", "normal": "a", "shifted": "A" },
    { "code": 5, "type": "keyboard", "normal": "b", "shifted": "B" },
    { "code": 6, "type": "keyboard", "normal": "c", "shifted": "C" },
    { "code": 7, "type": "keyboard", "normal": "d", "shifted": "D" },
    { "code": 8, "type": "keyboard", "normal": "e", "shifted": "E" },
    { "code": 9, "type": "keyboard", "normal": "f", "shifted": "F" },
    { "code": 10, "type": "keyboard", "normal": "g", "shifted": "G" },
    { "code": 11, "type": "keyboard", "normal": "h", "shifted": "H" },
    { "code": 12, "type": "keyboard", "normal": "i", "shifted": "I" },
    { "code": 13, "type": "keyboard", "normal": "j", "shifted": "J" },
    { "code": 14, "type": "keyboard", "normal": "k", "shifted": "K" },
    { "code": 15, "type": "keyboard", "normal": "l", "shifted": "L" },
    { "code": 16, "type": "keyboard", "normal": "m", "shifted": "M" },
    { "code": 17, "type": "keyboard", "normal": "n", "shifted": "N" },
    { "code": 18, "type": "keyboard", "normal": "o", "shifted": "O" },
    { "code": 19, "type": "keyboard", "normal": "p", "shifted": "P" },
    { "code": 20, "type": "keyboard", "normal": "q", "shifted": "Q" },
    { "code": 21, "type": "keyboard", "normal": "r", "shifted": "R" },
    { "code": 22, "type": "keyboard", "normal": "s", "shifted": "S" },
    { "code": 23, "type": "keyboard", "normal": "t", "shifted": "T" },
    { "code": 24, "type": "keyboard", "normal": "u", "shifted": "U" },
    { "code": 25, "type": "keyboard", "normal": "v", "shifted": "V" },
    { "code": 26, "type": "keyboard", "normal": "w", "shifted": "W" },
    { "code": 27, "type": "keyboard", "normal": "x", "shifted": "X" },
    { "code": 28, "type": "keyboard", "normal": "y", "shifted": "Y" },
    { "code": 29, "type": "keyboard", "normal": "z", "shifted": "Z" },
    { "code": 30, "type": "keyboard", "normal": "1", "shifted": "!" },
    { "code": 31, "type": "keyboard", "normal": "2", "shifted": "@" },
    { "code": 32, "type": "keyboard", "normal": "3", "shifted": "#" },
    { "code": 33, "type": "keyboard", "normal": "4", "shifted": "$" },
    { "code": 34, "type": "keyboard", "normal": "5", "shifted": "%" },
    { "code": 35, "type": "keyboard", "normal": "6", "shifted": "^" },
    { "code": 36, "type": "keyboard", "normal": "7", "shifted": "&" },
    { "code": 37, "type": "keyboard", "normal": "8", "shifted": "*" },
    { "code": 38, "type": "keyboard", "normal": "9", "shifted": "(" },
    { "code": 39, "type": "keyboard", "normal": "0", "shifted": ")" },
    { "code": 40, "type": "keyboard", "normal": "Return" },
    { "code": 41, "type": "keyboard", "normal": "Esc" },
    { "code": 42, "type": "keyboard", "normal": "Backspace" },
    { "code": 43, "type": "keyboard", "normal": "Tab" },
    { "code": 44, "type": "keyboard", "normal": "Spacebar" },
    { "code": 45, "type": "keyboard", "normal": "-", "shifted": "_" },
    { "code": 46, "type": "keyboard", "normal": "=", "shifted": "+" },
    { "code": 47, "type": "keyboard", "normal": "[", "shifted": "{" },
    { "code": 48, "type": "keyboard", "normal": "]", "shifted": "}" },
    { "code": 49, "type": "keyboard", "normal": "\\", "shifted": " | " },
    { "code": 50, "type": "keyboard", "normal": "Int' #", "shifted": "~" },
    { "code": 51, "type": "keyboard", "normal": ";", "shifted": ":" },
    { "code": 52, "type": "keyboard", "normal": "‘", "shifted": "“" },
    { "code": 53, "type": "keyboard", "normal": "`", "shifted": "~" },
    { "code": 54, "type": "keyboard", "normal": ",", "shifted": "<" },
    { "code": 55, "type": "keyboard", "normal": ".", "shifted": ">" },
    { "code": 56, "type": "keyboard", "normal": "/", "shifted": "?" },
    { "code": 57, "type": "keyboard", "normal": "Caps Lock" },
    { "code": 58, "type": "keyboard", "normal": "F1" },
    { "code": 59, "type": "keyboard", "normal": "F2" },
    { "code": 60, "type": "keyboard", "normal": "F3" },
    { "code": 61, "type": "keyboard", "normal": "F4" },
    { "code": 62, "type": "keyboard", "normal": "F5" },
    { "code": 63, "type": "keyboard", "normal": "F6" },
    { "code": 64, "type": "keyboard", "normal": "F7" },
    { "code": 65, "type": "keyboard", "normal": "F8" },
    { "code": 66, "type": "keyboard", "normal": "F9" },
    { "code": 67, "type": "keyboard", "normal": "F10" },
    { "code": 68, "type": "keyboard", "normal": "F11" },
    { "code": 69, "type": "keyboard", "normal": "F12" },
    { "code": 70, "type": "keyboard", "normal": "PScr" },
    { "code": 71, "type": "keyboard", "normal": "ScrLk" },
    { "code": 72, "type": "keyboard", "normal": "Pause" },
    { "code": 73, "type": "keyboard", "normal": "Ins" },
    { "code": 74, "type": "keyboard", "normal": "Home" },
    { "code": 75, "type": "keyboard", "normal": "PgUp" },
    { "code": 76, "type": "keyboard", "normal": "Del" },
    { "code": 77, "type": "keyboard", "normal": "End" },
    { "code": 78, "type": "keyboard", "normal": "PgDn" },
    { "code": 79, "type": "keyboard", "normal": "→" },
    { "code": 80, "type": "keyboard", "normal": "←" },
    { "code": 81, "type": "keyboard", "normal": "↓" },
    { "code": 82, "type": "keyboard", "normal": "↑" },
    { "code": 83, "type": "keypad", "normal": "NumLk", "shifted": "Clear" },
    { "code": 84, "type": "keypad", "normal": "/" },
    { "code": 85, "type": "keypad", "normal": "*" },
    { "code": 86, "type": "keypad", "normal": "-" },
    { "code": 87, "type": "keypad", "normal": "+" },
    { "code": 88, "type": "keypad", "normal": "Enter" },
    { "code": 89, "type": "keypad", "normal": "1", "shifted": "End" },
    { "code": 90, "type": "keypad", "normal": "2", "shifted": "↓" },
    { "code": 91, "type": "keypad", "normal": "3", "shifted": "PgDn" },
    { "code": 92, "type": "keypad", "normal": "4", "shifted": "←" },
    { "code": 93, "type": "keypad", "normal": "5" },
    { "code": 94, "type": "keypad", "normal": "6", "shifted": "→" },
    { "code": 95, "type": "keypad", "normal": "7", "shifted": "Home" },
    { "code": 96, "type": "keypad", "normal": "8", "shifted": "↑" },
    { "code": 97, "type": "keypad", "normal": "9", "shifted": "PgUp" },
    { "code": 98, "type": "keypad", "normal": "0", "shifted": "Ins" },
    { "code": 99, "type": "keypad", "normal": ".", "shifted": "Del" },
    { "code": 100, "type": "keyboard", "normal": "\\", "shifted": "|" },
    { "code": 101, "type": "keyboard", "normal": "Application" },
    { "code": 102, "type": "keyboard", "normal": "Power" },
    { "code": 103, "type": "keypad", "normal": "=" },
    { "code": 104, "type": "keyboard", "normal": "F13" },
    { "code": 105, "type": "keyboard", "normal": "F14" },
    { "code": 106, "type": "keyboard", "normal": "F15" },
    { "code": 107, "type": "keyboard", "normal": "F16" },
    { "code": 108, "type": "keyboard", "normal": "F17" },
    { "code": 109, "type": "keyboard", "normal": "F18" },
    { "code": 110, "type": "keyboard", "normal": "F19" },
    { "code": 111, "type": "keyboard", "normal": "F20" },
    { "code": 112, "type": "keyboard", "normal": "F21" },
    { "code": 113, "type": "keyboard", "normal": "F22" },
    { "code": 114, "type": "keyboard", "normal": "F23" },
    { "code": 115, "type": "keyboard", "normal": "F24" },
    { "code": 116, "type": "keyboard", "normal": "Execute" },
    { "code": 117, "type": "keyboard", "normal": "Help" },
    { "code": 118, "type": "keyboard", "normal": "Menu" },
    { "code": 119, "type": "keyboard", "normal": "Select" },
    { "code": 120, "type": "keyboard", "normal": "Stop" },
    { "code": 121, "type": "keyboard", "normal": "Again" },
    { "code": 122, "type": "keyboard", "normal": "Undo" },
    { "code": 123, "type": "keyboard", "normal": "Cut" },
    { "code": 124, "type": "keyboard", "normal": "Copy" },
    { "code": 125, "type": "keyboard", "normal": "Paste" },
    { "code": 126, "type": "keyboard", "normal": "Find" },
    { "code": 127, "type": "keyboard", "normal": "Mute" },
    { "code": 128, "type": "keyboard", "normal": "VolUp" },
    { "code": 129, "type": "keyboard", "normal": "VolDn" },
    { "code": 130, "type": "lock", "normal": "CapsLk" },
    { "code": 131, "type": "lock", "normal": "NumLk" },
    { "code": 132, "type": "lock", "normal": "ScrLk" },
    { "code": 133, "type": "keypad", "normal": "," },
    { "code": 134, "type": "keypad", "normal": "= AS/400," },
    { "code": 135, "type": "unknow", "normal": "135" },
    { "code": 136, "type": "unknow", "normal": "136" },
    { "code": 137, "type": "unknow", "normal": "137" },
    { "code": 138, "type": "unknow", "normal": "138" },
    { "code": 139, "type": "unknow", "normal": "139" },
    { "code": 140, "type": "unknow", "normal": "140" },
    { "code": 141, "type": "unknow", "normal": "141" },
    { "code": 142, "type": "unknow", "normal": "142" },
    { "code": 143, "type": "unknow", "normal": "143" },
    { "code": 144, "type": "unknow", "normal": "144" },
    { "code": 145, "type": "unknow", "normal": "145" },
    { "code": 146, "type": "unknow", "normal": "146" },
    { "code": 147, "type": "unknow", "normal": "147" },
    { "code": 148, "type": "unknow", "normal": "148" },
    { "code": 149, "type": "unknow", "normal": "149" },
    { "code": 150, "type": "unknow", "normal": "150" },
    { "code": 151, "type": "unknow", "normal": "151" },
    { "code": 152, "type": "unknow", "normal": "152" },
    { "code": 153, "type": "keyboard", "normal": "AltErase" },
    { "code": 154, "type": "keyboard", "normal": "SysRq" },
    { "code": 155, "type": "keyboard", "normal": "Cancel" },
    { "code": 156, "type": "keyboard", "normal": "Clear" },
    { "code": 157, "type": "keyboard", "normal": "Prior" },
    { "code": 158, "type": "keyboard", "normal": "Return" },
    { "code": 159, "type": "keyboard", "normal": "Separator" },
    { "code": 160, "type": "keyboard", "normal": "Out" },
    { "code": 161, "type": "keyboard", "normal": "Oper" },
    { "code": 162, "type": "keyboard", "normal": "Clear/Again" },
    { "code": 163, "type": "keyboard", "normal": "ClSel/Props" },
    { "code": 164, "type": "keyboard", "normal": "ExSel" },
    { "code": 165, "type": "unknow", "normal": "165" },
    { "code": 166, "type": "unknow", "normal": "166" },
    { "code": 167, "type": "unknow", "normal": "167" },
    { "code": 168, "type": "unknow", "normal": "168" },
    { "code": 169, "type": "unknow", "normal": "169" },
    { "code": 170, "type": "unknow", "normal": "170" },
    { "code": 171, "type": "unknow", "normal": "171" },
    { "code": 172, "type": "unknow", "normal": "172" },
    { "code": 173, "type": "unknow", "normal": "173" },
    { "code": 174, "type": "unknow", "normal": "174" },
    { "code": 175, "type": "unknow", "normal": "175" },
    { "code": 176, "type": "keypad", "normal": "00" },
    { "code": 177, "type": "keypad", "normal": "000" },
    { "code": 178, "type": "unknow", "normal": "178" },
    { "code": 179, "type": "unknow", "normal": "179" },
    { "code": 180, "type": "unknow", "normal": "180" },
    { "code": 181, "type": "unknow", "normal": "181" },
    { "code": 182, "type": "keypad", "normal": "(" },
    { "code": 183, "type": "keypad", "normal": ")" },
    { "code": 184, "type": "keypad", "normal": "{" },
    { "code": 185, "type": "keypad", "normal": "}" },
    { "code": 186, "type": "keypad", "normal": "Tab" },
    { "code": 187, "type": "keypad", "normal": "Backspace" },
    { "code": 188, "type": "keypad", "normal": "A" },
    { "code": 189, "type": "keypad", "normal": "B" },
    { "code": 190, "type": "keypad", "normal": "C" },
    { "code": 191, "type": "keypad", "normal": "D" },
    { "code": 192, "type": "keypad", "normal": "E" },
    { "code": 193, "type": "keypad", "normal": "F" },
    { "code": 194, "type": "keypad", "normal": "XOR" },
    { "code": 195, "type": "keypad", "normal": "^" },
    { "code": 196, "type": "keypad", "normal": "%" },
    { "code": 197, "type": "keypad", "normal": "<" },
    { "code": 198, "type": "keypad", "normal": ">" },
    { "code": 199, "type": "keypad", "normal": "&" },
    { "code": 200, "type": "keypad", "normal": "&&" },
    { "code": 201, "type": "keypad", "normal": "|" },
    { "code": 202, "type": "keypad", "normal": "||" },
    { "code": 203, "type": "keypad", "normal": ":" },
    { "code": 204, "type": "keypad", "normal": "#" },
    { "code": 205, "type": "keypad", "normal": "Space" },
    { "code": 206, "type": "keypad", "normal": "@" },
    { "code": 207, "type": "keypad", "normal": "!" },
    { "code": 208, "type": "keypad", "normal": "Mem Store" },
    { "code": 209, "type": "keypad", "normal": "Mem Recall" },
    { "code": 210, "type": "keypad", "normal": "Mem Clear" },
    { "code": 211, "type": "keypad", "normal": "Mem Add" },
    { "code": 212, "type": "keypad", "normal": "Mem Subtract" },
    { "code": 213, "type": "keypad", "normal": "Mem Multiply" },
    { "code": 214, "type": "keypad", "normal": "Mem Divide" },
    { "code": 215, "type": "keypad", "normal": "+/-" },
    { "code": 216, "type": "keypad", "normal": "Clear" },
    { "code": 217, "type": "keypad", "normal": "Clear Entry" },
    { "code": 218, "type": "keypad", "normal": "Binary" },
    { "code": 219, "type": "keypad", "normal": "Octal" },
    { "code": 220, "type": "keypad", "normal": "Decimal" },
    { "code": 221, "type": "keypad", "normal": "Hexadecimal" },
    { "code": 222, "type": "unknow", "normal": "222" },
    { "code": 223, "type": "unknow", "normal": "223" },
    { "code": 224, "type": "keyboard", "normal": "L Ctrl" },
    { "code": 225, "type": "keyboard", "normal": "L Shift" },
    { "code": 226, "type": "keyboard", "normal": "L Alt" },
    { "code": 227, "type": "keyboard", "normal": "L OS" },
    { "code": 228, "type": "keyboard", "normal": "R Ctrl" },
    { "code": 229, "type": "keyboard", "normal": "R Shift" },
    { "code": 230, "type": "keyboard", "normal": "R Alt" },
    { "code": 231, "type": "keyboard", "normal": "R OS" },
    { "code": 232, "type": "unknow", "normal": "232" },
    { "code": 233, "type": "unknow", "normal": "233" },
    { "code": 234, "type": "unknow", "normal": "234" },
    { "code": 235, "type": "unknow", "normal": "235" },
    { "code": 236, "type": "unknow", "normal": "236" },
    { "code": 237, "type": "unknow", "normal": "237" },
    { "code": 238, "type": "unknow", "normal": "238" },
    { "code": 239, "type": "unknow", "normal": "239" },
    { "code": 240, "type": "unknow", "normal": "240" },
    { "code": 241, "type": "unknow", "normal": "241" },
    { "code": 242, "type": "unknow", "normal": "242" },
    { "code": 243, "type": "unknow", "normal": "243" },
    { "code": 244, "type": "unknow", "normal": "244" },
    { "code": 245, "type": "unknow", "normal": "245" },
    { "code": 246, "type": "unknow", "normal": "246" },
    { "code": 247, "type": "unknow", "normal": "247" },
    { "code": 248, "type": "unknow", "normal": "248" },
    { "code": 249, "type": "unknow", "normal": "249" },
    { "code": 250, "type": "unknow", "normal": "250" },
    { "code": 251, "type": "unknow", "normal": "251" },
    { "code": 252, "type": "unknow", "normal": "252" },
    { "code": 253, "type": "unknow", "normal": "253" },
    { "code": 254, "type": "unknow", "normal": "254" },
    { "code": 255, "type": "unknow", "normal": "255" },
]
export default scancodes;
